### ISSUE TITLE
[Payment] 결제 API선정 및 조사

### ISSUE THREAD

**Issue by Seulah-coder** [mygoodsupporter/mygoodsupporter#116]
##1.결제 API선정
-아임포트
[아임포트 깃허브](https://github.com/iamport/iamport-manual)
[아임포트 개발자 가이드](https://guide.iamport.kr/418a8dd5-6b84-419d-8d1b-ffd311b36404)
-부트페이
[부트페이 사이트](https://www.bootpay.co.kr/)
[부트페이 진행하기 문서](https://docs.bootpay.co.kr/)
[부트페이 깃허브](https://github.com/bootpay/bootpay_js)

**Comment by Seulah-coder** [comment]
[아임포트 검증하기](https://tyrannocoding.tistory.com/44?category=896661)
[부트페이 검증하기](https://tyrannocoding.tistory.com/11?category=896661)

**Comment by safecorners** [comment]
[아임포트 카카오페이 결제](https://github.com/iamport/iamport-manual/blob/master/인증결제/sample/kakao.md)

**Comment by Seulah-coder** [comment]
아임포트로 결제 진행하는게 예시가 많고 테스트 진행이 쉬울것 같아서 아임포트로 진행하겠습니다.
