### ISSUE TITLE
GET'/projects/:username/:projectId/edit/basics

### ISSUE THREAD

**Issue by sindy970** [mygoodsupporter/mygoodsupporter#121]

**Comment by safecorners** [comment]
[jstl에서 localdatetime 사용하기](https://kimseungjae.tistory.com/6)
[Spring-MVC-게시판-제작-시-JSP에서-LocalDateTime-포맷-변경하기](https://pro-pennek.tistory.com/entry/Spring-MVC-%EA%B2%8C%EC%8B%9C%ED%8C%90-%EC%A0%9C%EC%9E%91-%EC%8B%9C-JSP%EC%97%90%EC%84%9C-LocalDateTime-%ED%8F%AC%EB%A7%B7-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0)

https://github.com/sargue/java-time-jsptags
