### ISSUE TITLE
MyBatis 공식 문서 읽기

### ISSUE THREAD

**Issue by Seulah-coder** [mygoodsupporter/mygoodsupporter#20]
- [x] [Mapper XML 파일](https://mybatis.org/mybatis-3/ko/sqlmap-xml.html)
- [x] [MyBatis Spring](https://mybatis.org/spring/ko/getting-started.html)
- [x] [MyBatis ORM처럼 사용하기](https://lyb1495.tistory.com/110)

**Comment by Seulah-coder** [comment]
- [x] resultMap
- [x] association
- [x] collection

**Comment by safecorners** [comment]
[foreach 구문, parameterType List, Model, Map 사용](https://linked2ev.github.io/mybatis/2020/01/05/MyBatis-5-foreach-%EA%B5%AC%EB%AC%B8,-parameterType-List-Model-Map/)
