### ISSUE TITLE
레이아웃/유효성검사/디비 참조관계 역할분담!!

### ISSUE THREAD

**Issue by Seulah-coder** [mygoodsupporter/mygoodsupporter#31]
레이아웃 - 수빈
유효성검사 - 슬아
디비 참조관계 - 승희

**Comment by safecorners** [comment]
[AUTO_INCREMENT - LAST_INSERT_ID](https://mariadb.com/kb/en/last_insert_id/)
[시퀀스](https://mariadb.com/kb/ko/sequence-overview/)

**Comment by safecorners** [comment]
역할 분담이 끝났으니 닫습니다

**Comment by safecorners** [comment]
역할 분담이 끝났으니 닫습니다
