### ISSUE TITLE
CSS Framework

### ISSUE THREAD

**Issue by tnqls9582** [mygoodsupporter/mygoodsupporter#32]
1. [bootstrap](http://bootstrapk.com/)
2. [bulma](https://bulma.io/)
3. [tachyons](https://tachyons.io/)

**Comment by Seulah-coder** [comment]
4.[tailblocks](https://tailblocks.cc/)로 진행

1.  복사 붙여넣기 후 수정이 간편하다.
2.  반응형도 가능
3.  사람들이 만든 오픈 소스가 많음

**Comment by tnuren** [comment]
### Tailwind
- [ ] [Tailwind CSS Crash Course](https://www.youtube.com/watch?v=UBOj6rqRUME&list=RDCMUC29ju8bIPH5as8OGnQzwJyA&start_radio=1)
- [ ] [Tailwind CSS Tutorial for Beginners - Full Course](https://www.youtube.com/watch?v=4wGmylafgM4)
- [ ] [Tailwind CSS tutorial - Learn how to build websites using a utility-first CSS framework](https://themesberg.com/blog/tailwind-css/tutorial)
- [ ] [Learn Tailwind CSS - A Beginner's Guide](https://wsvincent.com/learn-tailwind-css-beginners-guide/)
- [ ] [Get Started with Tailwind CSS in 15 Minutes](https://scotch.io/tutorials/get-started-with-tailwind-css-in-15-minutes)
