### ISSUE TITLE
[CI/CD]SpringBoot Migration

### ISSUE THREAD

**Issue by Seulah-coder** [mygoodsupporter/mygoodsupporter#42]
- [x] Spring Boot
- [x] [JSP](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-web-applications.spring-mvc.template-engines)
- [x] MyBatis
- [x] Spring Security

**Comment by safecorners** [comment]
- [x] [Spring Boot Maven Plugin Documentation](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/)
- [x] [Spring Boot With JSPs in Executable Jars](https://dzone.com/articles/spring-boot-with-jsps-in-executable-jars-1) 
- [x] [Spring MVC - JSP 프로젝트를 Spring Boot로 옮기기](https://github.com/HomoEfficio/dev-tips/blob/master/SpringMVC-JSP%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EB%A5%BC%20SpringBoot%EB%A1%9C%20%EC%98%AE%EA%B8%B0%EA%B8%B0.md)
- [x] [mybatis-spring-boot-starter](https://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/)
- [x] [Spring Boot + MyBatis 설정 방법](https://atoz-develop.tistory.com/entry/Spring-Boot-MyBatis-%EC%84%A4%EC%A0%95-%EB%B0%A9%EB%B2%95)

**Comment by safecorners** [comment]
> Plugin 'org.springframework.boot:spring-boot-maven-plugin:' not found

스프링부트 메이븐 플러그인의 버전을 명시하지 않아서 생기는 문제입니다.
maven effective-pom 명령어로 버전을 찾은 다음 버전 정보를 적어줍니다.

**Comment by safecorners** [comment]
> Cannot resolve MVC View 

어플리케이션을 jar로 패키징하면 `src/main/resources/META-INF/resources/WEB-INF/*` 경로로 우회해서 뷰템플릿을 저장해야하는데 우회해서 저장하면 IDE의 코드 인텔리전스가 경로를 제대로 인식하지 못한다. jsp가 아닌 다른 템플릿엔진을 사용하거나 코드 인텔리전스의 도움을 받지 않는다면 생산성이 떨어지므로 War로 배포하기로 결정하였다.
