### ISSUE TITLE
[Util]Amazon S3 이미지 업로드

### ISSUE THREAD

**Issue by safecorners** [mygoodsupporter/mygoodsupporter#56]
@sindy970 
- [x] amazon aws 가입하기
- [x] s3 bucket 설정
- [x] maven aws 의존성 추가
- [x] 인증정보 우아하게 추가하기
- [x] MultipartFile을 사용자로 부터 전달 받기
- [x] S3에 전달할 수 있도록 MultiPartFile을 File로 전환
                 (S3에 Multipartfile 타입은 전송이 안됩니다.)
- [x] 전환된 File을 S3에 public 읽기 권한으로 put 
                (외부에서 정적 파일을 읽을 수 있도록 하기 위함입니다.)
- [x] 로컬에 생성된 File 삭제 
                (Multipartfile -> File로 전환되면서 로컬에 파일 생성된것을 삭제합니다.)
- [x] 업로드된 파일의 S3 URL 주소를 반환

@Seulah-coder 
- [x] Amazon AWS Free tier 가입하기
- [x] Organization 생성
- [x] IAM 계정 생성 및 Credential key 발급
- [x] IAM 권한 제한 
- [x] 2-Factor Authentication 활성화
- [x] S3.버킷 생성(Region: ap-northeast-2)

**Comment by sindy970** [comment]
1. amazon aws회원 가입 
2. s3 bucket 설정 
            bucket name => mygoodsupporter
3. pom.xml에 의존성 주입
```xml
`<dependency>`
				`<groupId>com.amazonaws</groupId>`
				`<artifactId>aws-java-sdk</artifactId>`
				`<version>1.11.106</version>`
			`</dependency>`
			`<dependency>`
				`<groupId>jca</groupId>`
				`<artifactId>jca</artifactId>`
				`<version>1.5</version>`
			`</dependency>`
```xml
spring-cloud-starter-aws를 추가하기로 했음

**Comment by safecorners** [comment]
https://jojoldu.tistory.com/300
https://victorydntmd.tistory.com/m/334

**Comment by safecorners** [comment]
### Reference
- [AWS SDK for Java 2.0 documentation examples](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javav2)
- [AWS SDK for JavaDeveloper Guide PDF](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/aws-sdk-java-dg-v2.pdf)
- [AWS SDK for Java](https://aws.amazon.com/sdk-for-java/)
- [Getting started with Spring Boot on AWS: Part 1](https://aws.amazon.com/blogs/opensource/getting-started-with-spring-boot-on-aws-part-1/)
- [Creating your first AWS Java web application](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javav2/usecases/creating_first_project)
- [Spring Cloud AWS Gitter](https://gitter.im/spring-cloud/spring-cloud-aws)

### Blog
- [SpringBoot & AWS S3 연동하기](https://jojoldu.tistory.com/300)
- [AWS S3 연동 (1) - 파일 업로드 기본 (AmazonS3ClientBuilder)](https://victorydntmd.tistory.com/m/334)
- [Spring Boot AWS S3 사진 업로드 하는 법](https://devlog-wjdrbs96.tistory.com/m/323)
- [Spring Boot | S3 파일 업로드](https://gaemi606.tistory.com/entry/Spring-Boot-S3-%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C)
- [Spring boot를 이용한 AWS S3 파일 업로드하기](https://willseungh0.tistory.com/2)
- [Spring Cloud AWS S3 연동 및 파일 업로드](https://willseungh0.tistory.com/78)
- [AWS EC2 + Spring boot (8) - AWS S3 이미지 파일 업로드](https://klyhyeon.tistory.com/170)
- [AWS S3 with Java](https://www.baeldung.com/aws-s3-java)
- [Spring Boot, Amazon S3 버킷에 파일 업로드, 다운로드하기](https://jsonobject.tistory.com/523)

**Comment by safecorners** [comment]
### Spring Cloud Start AWS 의존성 추가
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-aws</artifactId>
	<version>2.2.6.RELEASE</version>
</dependency>
```

https://spring.io/projects/spring-cloud
```xml
<properties>
	<spring-cloud.version>2020.0.3</spring-cloud.version>
</properties>

<dependencies>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-aws</artifactId>
	</dependency>
</dependencies>

<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>${spring-cloud.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

[Getting started with Spring Boot on AWS: Part 1](https://aws.amazon.com/blogs/opensource/getting-started-with-spring-boot-on-aws-part-1/)

**Comment by safecorners** [comment]
의존성은 추가됐지만 메타데이터를 설정해주지 않아 런타임오류가 발생함

**Comment by safecorners** [comment]
[1. Using Amazon Web Services](https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/index.html)


**Spring Cloud AWS Core** is the core module of Spring Cloud AWS providing basic services for security and configuration setup. Developers will not use this module directly but rather through other modules. The core module provides support for cloud based environment configurations providing direct access to the instance based EC2 metadata and the overall application stack specific CloudFormation metadata.

**Spring Cloud AWS Context** delivers access to the Simple Storage Service via the Spring resource loader abstraction. Moreover developers can send e-mails using the Simple E-Mail Service and the Spring mail abstraction. Further the developers can introduce declarative caching using the Spring caching support and the ElastiCache caching service.

**Comment by safecorners** [comment]
[AWS SDK for JavaDeveloper Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/aws-sdk-java-dg-v2.pdf)
[awsdocs / aws-doc-sdk-examples](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javav2/usecases/creating_first_project)

**Comment by safecorners** [comment]
### 1. EC2 Metadata Exception
#### 에러
com.amazonaws.SdkClientException at org.springframework.cloud.aws.core.region.Ec2MetadataRegionProvider.getRegion(Ec2MetadataRegionProvider.java:39) ~[spring-cloud-aws-core-2.2.6.RELEASE.jar:2.2.6.RELEASE]

com.amazonaws.util.EC2MetadataUtils      : Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). Failed to connect to service endpoint: 

#### 해결
```yaml
spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
```

#### 참고
- [SpringBoot & AWS S3 연동하기](https://github.com/jojoldu/blog-comments/issues/252)
- [Spring Cloud AWS - Unable to retrieve the requested metadata](https://kjgleh.github.io/spring/2018/07/09/spring-cloud-aws-Unable-to-retrieve-the-requested-metadata.html)
- [Unable to retrieve the requested metadata /latest/meta-data/public-hostname](https://stackoverflow.com/questions/56987939/unable-to-retrieve-the-requested-metadata-latest-meta-data-public-hostname)
- [Spring boot cannot start with aws starter dependency](https://stackoverflow.com/questions/58022282/spring-boot-cannot-start-with-aws-starter-dependency)

### 2. CloudeFormation Exception
#### 에러
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.aws.core.env.ResourceIdResolver.BEAN_NAME': Invocation of init method failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'stackResourceRegistryFactoryBean' defined in class path resource [org/springframework/cloud/aws/autoconfigure/context/ContextStackAutoConfiguration.class]: Unsatisfied dependency expressed through method 'stackResourceRegistryFactoryBean' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonCloudFormation' defined in class path resource [org/springframework/cloud/aws/autoconfigure/context/ContextStackAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: There is no EC2 meta data available, because the application is not running in the EC2 environment. Region detection is only possible if the application is running on a EC2 instance

#### 해결
application.yaml
```yaml
cloud:
  aws:
    stack:
      auto: false
```

#### 참고
- [CloudFormation configuration in Spring Boot](https://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_cloudformation_configuration_in_spring_boot)

### 3. S3 Configuration Exception
#### 에러
 ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3': Invocation of init method failed; nested exception is java.lang.IllegalStateException: There is no EC2 meta data available, because the application is not running in the EC2 environment. Region detection is only possible if the application is running on a EC2 instance

#### 해결
```yaml
cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
```
로컬 환경에서는 ec2 meta-data 디스커버리 기능을 사용할수 없음.

#### 참고
- [Disable Spring Cloud AWS autoconfiguration for local development](https://stackoverflow.com/questions/50763767/disable-spring-cloud-aws-autoconfiguration-for-local-development)
- [Spring Cloud AWS Region Configuration](https://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_region_configuration)

**Comment by Seulah-coder** [comment]
가입 완료후 팀챗으로 코드 공유함

**Comment by sindy970** [comment]
[Spring Boot 파일 업로드 MultipartFile](https://gofnrk.tistory.com/36)
