### ISSUE TITLE
[CI/CD]Git flow 이해하기

### ISSUE THREAD

**Issue by safecorners** [mygoodsupporter/mygoodsupporter#74]
- [x] [Git Flow 개념 이해하기](https://uxgjs.tistory.com/183)
- [x] [git-flow cheatsheet](https://danielkummer.github.io/git-flow-cheatsheet/index.ko_KR.html)
- [x] [git-flow 소개, 설치 및 사용법](https://hbase.tistory.com/60)
- [ ] [Git Flow와 자주 사용되는 Git 명령어들](https://www.holaxprogramming.com/2018/11/01/git-commands/)
- [ ] [협업을 위한 Git Flow 설정하기](https://overcome-the-limits.tistory.com/entry/%ED%98%91%EC%97%85-%ED%98%91%EC%97%85%EC%9D%84-%EC%9C%84%ED%95%9C-Git-Flow-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)
- [ ] [협업을 위한 git 커밋컨벤션 설정하기](https://overcome-the-limits.tistory.com/entry/%ED%98%91%EC%97%85-%ED%98%91%EC%97%85%EC%9D%84-%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8-git-%EC%BB%A4%EB%B0%8B%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0?category=911197)
- [x] [GIT Commit Message Conventions에 대해 알아보자](https://velog.io/@new_wisdom/Clean-Coding-Commit-Message-Conventions)

**Comment by Seulah-coder** [comment]
- [x]  Git Flow 개념 이해하기
- [ ]  git-flow cheatsheet
- [ ]  git-flow 소개, 설치 및 사용법
- [x]  Git Flow와 자주 사용되는 Git 명령어들
- [ ]  협업을 위한 Git Flow 설정하기
- [x]  협업을 위한 git 커밋컨벤션 설정하기
- [x]  GIT Commit Message Conventions에 대해 알아보자
