### ISSUE TITLE
[Documentation] 오류 처리 전략

### ISSUE THREAD

**Issue by safecorners** [mygoodsupporter/mygoodsupporter#84]
1. [Exception Guide](https://cheese10yun.github.io/spring-guide-exception/)
2. [Validation and Exception Handling with Spring](https://medium.com/sprang/validation-and-exception-handling-with-spring-ba44b3ee0723)
3. [Validating inner layers with Spring](https://medium.com/sprang/validating-inner-layers-with-spring-7216b7f221f)

**Comment by Seulah-coder** [comment]
- [x] Exception Guide
- [x] Validation and Exception Handling with Spring
- [x] Validating inner layers with Spring
